# Generated by Django 3.1.5 on 2021-05-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrappingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=200, null=True)),
                ('plateform', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('influancer', models.CharField(blank=True, max_length=200, null=True)),
                ('channel_name', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('subscriber', models.CharField(blank=True, max_length=200, null=True)),
                ('avg_view', models.CharField(blank=True, max_length=200, null=True)),
                ('feature', models.CharField(blank=True, max_length=200, null=True)),
                ('review', models.CharField(blank=True, max_length=200, null=True)),
                ('pokar', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=200, null=True)),
                ('email_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
