# Generated by Django 3.1.5 on 2021-05-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrappingdata',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
